title: Tillys Hundeleben
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: http://brigitbardot.github.io
baseurl: "/long-haul"
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   instagram: tillykokoni/
   twitter: TillyTheKokoni
   facebook: profile.php?id=100011346237203
   email: tillythekokoni@web.de

google_analytics: "UA-58263416-1"
